(selectdb-cloud) Fix missing CloudCluster field in`ShowProcesslistStmt` result  when show all fe connection (#3304)
```
  java.lang.NumberFormatException: Invalid integer format for value 'Query'
  at com.mysql.cj.protocol.a.MysqlTextValueDecoder.getLong(MysqlTextValueDecoder.java:232)
  at com.mysql.cj.protocol.a.MysqlTextValueDecoder.getInt(MysqlTextValueDecoder.java:161)
  ...
```