[fix](group commit) fix insert_group_commit_into and fix write to internal schema (#3254)
1. 
```
Exception:
java.sql.SQLException: errCode = 2, detailMessage = The table [insert_group_commit_into_mv]'s state is ROLLUP, cannot be dropped. please cancel the operation on olap table firstly. If you want to forcibly drop(cannot be recovered), please use "DROP table FORCE".
  at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
  at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
  at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
  at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:371)
  at java_sql_PreparedStatement$execute.call(Unknown Source)
  at org.apache.doris.regression.util.JdbcUtils$_executeToList_closure1.doCall(JdbcUtils.groovy:31)
  at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
```

2. when write to insternal schema
```
W0326 20:11:38.896462 2222471 group_commit_mgr.cpp:255] create group commit load error, st=[INTERNAL_ERROR]TStatus: errCode = 2, detailMessage = Not allowed to operate database: default_cluster:
__internal_schema
```